# config/basecamp.yml
defaults: &defaults
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  client_id: '033e1be1c051167958a4ecac9792b4b353e10098'
  client_secret: 'a4fe920e7604a6a4ceacababd98114ffac03b93d'
  redirect_url: 'http://localhost:3000/oauth/request_token'
  site: 'https://launchpad.37signals.com/authorization/new'
  change_user: FALSE
  account_id: '1937153'

development:
  <<: *defaults
  neat_setting: 800
  cool:
    saweet: nested settings

test:
  <<: *defaults

production:
  <<: *defaults